app = 'weather-family'
primary_region = 'iad'
console_command = 'bash'

[env]
  DEFAULT_LOCALE = "en"
  DISABLE_DATABASE_ENVIRONMENT_CHECK = "1"
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "enabled"
  MAX_THREADS = "5"

[deploy]
  strategy = "bluegreen"

[[statics]]
  guest_path = "/opt/mastodon/public"
  url_prefix = "/"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "connections"
    hard_limit = 30
    soft_limit = 12

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    timeout = "2s"
    tls_skip_verify = false

  [[services.http_checks]]
    method = "get"
    protocol = "http"
    path = "/health"
    grace_period = "1s"
    interval = "15s"
    timeout = "2s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
