# fly.toml app configuration file generated for weather-family-db on 2024-10-31T20:40:48-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weather-family-db'
primary_region = 'iad'

[env]
  PRIMARY_REGION = 'iad'

[[mounts]]
  source = 'pg_data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 5432
  auto_start_machines = true
  auto_stop_machines = 'suspend'
  min_machines_running = 1

  [[services.ports]]
    port = 5432
    handlers = ['pg_tls']

  [services.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 25

[[services]]
  protocol = 'tcp'
  internal_port = 5433
  auto_start_machines = true
  auto_stop_machines = 'suspend'
  min_machines_running = 1

  [[services.ports]]
    port = 5433
    handlers = ['pg_tls']

  [services.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 20

[checks]
  [checks.pg]
    port = 5500
    type = 'http'
    interval = '15s'
    timeout = '10s'
    path = '/flycheck/pg'

  [checks.role]
    port = 5500
    type = 'http'
    interval = '15s'
    timeout = '10s'
    path = '/flycheck/role'

  [checks.vm]
    port = 5500
    type = 'http'
    interval = '15s'
    timeout = '10s'
    path = '/flycheck/vm'

[[metrics]]
  port = 9187
  path = '/metrics'
  https = false
